# Generated by Django 6.0 on 2026-01-15 05:44

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pan', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]$', 'Invalid PAN format')])),
                ('gstin', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Invalid GSTIN format')])),
                ('financial_year_start', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_draft_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='onboarding', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Actual business owner / client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'bmp', 'tiff'])])),
                ('doc_type', models.CharField(choices=[('receipt', 'Receipt/Invoice'), ('bank', 'Bank Statement'), ('other', 'Other')], default='receipt', max_length=20)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_number', models.CharField(blank=True, help_text='Invoice / reference number', max_length=100, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, help_text='Used to detect duplicate uploads', max_length=64, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.business')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gst_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=200, null=True)),
                ('ledger_account', models.CharField(blank=True, max_length=100, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.document')),
            ],
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['created_by'], name='core_busine_created_260be4_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='core_busine_owner_i_3dfbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status'], name='core_busine_status_ebf13f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['financial_year_start'], name='core_busine_financi_9939f3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business'], name='core_docume_busines_4c79f9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='core_docume_uploade_8c924b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_type'], name='core_docume_doc_typ_a55021_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='core_docume_documen_19a7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['document'], name='core_extrac_documen_4b8a28_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['vendor'], name='core_extrac_vendor_94b9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['invoice_no'], name='core_extrac_invoice_1b6fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['ledger_account'], name='core_extrac_ledger__7d4874_idx'),
        ),
    ]
