# Generated by Django 6.0 on 2026-01-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, help_text="Company's registered state (for GST POS logic)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='vendor_gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
