# Generated by Django 6.0 on 2026-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_address_business_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extraction_errors',
            field=models.JSONField(blank=True, default=dict, help_text='List of issues found during AI processing'),
        ),
    ]
