# Generated by Django 6.0 on 2026-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_extraction_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedlineitem',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
