# Generated by Django 6.0 on 2026-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_extractedlineitem_credit_extractedlineitem_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedlineitem',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
