# Generated by Django 6.0 on 2026-01-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_extractedlineitem_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_synced_to_tally',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='sync_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
