# Generated by Django 6.0 on 2026-01-18 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_is_synced_to_tally_document_sync_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Invalid GSTIN format')]),
        ),
    ]
