# Generated by Django 6.0 on 2026-01-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_business_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='AI Confidence Score (0-100)'),
        ),
    ]
