# Generated by Django 6.0 on 2026-01-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_document_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accounting_logic',
            field=models.TextField(blank=True, help_text="AI's Chain-of-thought logic for audit trails", null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_b2b',
            field=models.BooleanField(default=False, help_text="True if Business's GSTIN is present on the bill"),
        ),
        migrations.AddField(
            model_name='document',
            name='is_msme',
            field=models.BooleanField(default=False, help_text='Detected if Vendor is MSME registered'),
        ),
        migrations.AddField(
            model_name='document',
            name='payment_deadline',
            field=models.DateField(blank=True, help_text='Hard 45-day MSME deadline (Section 43B(h))', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='udyam_number',
            field=models.CharField(blank=True, help_text='Udyam Registration Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='tds_rate',
            field=models.CharField(blank=True, help_text='e.g. 10% or 2%', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ocr_complete', 'OCR Complete'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=50),
        ),
    ]
