# Generated by Django 6.0 on 2026-01-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document_accounting_logic_document_is_b2b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_intercompany_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='core.business'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores PDF Author/Producer to catch collusion (ERR-351)'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_suspicious',
            field=models.BooleanField(default=False, help_text='Master flag for Forensic Dashboard'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_trusted_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='suspicion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_ip',
            field=models.GenericIPAddressField(blank=True, help_text="Detects 'Internal IP' fraud (ERR-404)", null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Detects hardware fingerprint consistency (ERR-396)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vendor_domain_age',
            field=models.IntegerField(blank=True, help_text='Flags recently registered domains (ERR-253)', null=True),
        ),
    ]
