# Generated by Django 6.0 on 2026-01-23 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_business_is_intercompany_enabled_business_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_busines_4c79f9_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='is_suspicious',
            field=models.BooleanField(db_index=True, default=False, help_text='Master flag for Forensic Dashboard'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business', 'uploaded_at'], name='core_docume_busines_395e38_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business', 'is_suspicious'], name='core_docume_busines_e34301_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business', 'status'], name='core_docume_busines_7693a4_idx'),
        ),
    ]
