# Generated by Django 6.0 on 2026-01-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document_accounting_logic_document_is_b2b_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='extracted_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.extractedlineitem'),
        ),
    ]
