# Generated by Django 6.0 on 2026-01-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='ref_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='ref_type',
            field=models.CharField(blank=True, choices=[('NEW', 'New Ref'), ('AGST', 'Against Ref'), ('ADV', 'Advance'), ('ON_ACC', 'On Account')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
