# Generated by Django 6.0 on 2026-01-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_extraction_errors'),
        ('ledger', '0002_journalentry_ref_number_journalentry_ref_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='core.document'),
        ),
    ]
