# Generated by Django 6.0 on 2026-01-18 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_extraction_errors'),
        ('ledger', '0003_voucher_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='is_revenue_nature',
            field=models.BooleanField(default=False, help_text='True for P&L items (Income/Expense), False for Balance Sheet'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], max_length=20),
        ),
        migrations.CreateModel(
            name='VoucherSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal'), ('CREDIT_NOTE', 'Credit Note'), ('DEBIT_NOTE', 'Debit Note')], max_length=20)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('current_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
            options={
                'unique_together': {('business', 'voucher_type', 'prefix')},
            },
        ),
    ]
