# Generated by Django 6.0 on 2026-01-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_is_synced_to_tally_document_sync_log_and_more'),
        ('ledger', '0004_accountgroup_is_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.document'),
        ),
    ]
