# Generated by Django 6.0 on 2026-01-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_voucher_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='classification',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='ASSET', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='is_system_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='fingerprint',
            field=models.CharField(blank=True, help_text='hash(vendor + invoice_no + date + total_amount)', max_length=255, null=True, unique=True),
        ),
    ]
