# Generated by Django 6.0 on 2026-01-18 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_account_classification_account_is_system_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ledger.accountgroup'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.financialyear'),
        ),
    ]
