# Generated by Django 6.0 on 2026-01-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_business_gstin'),
        ('ledger', '0007_alter_account_group_alter_journalentry_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.business'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='core.business'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_vouchers', to='core.business'),
        ),
    ]
