# Generated by Django 6.0 on 2026-01-22 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document_accounting_logic_document_is_b2b_and_more'),
        ('ledger', '0008_alter_account_business_alter_accountgroup_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('particulars', models.TextField(help_text="Flattened summary like 'Dr Bank To Sales'")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_book_entries', to='core.business')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day_book_entry', to='ledger.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitAndLossSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('income_json', models.JSONField()),
                ('expense_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
        ),
        migrations.CreateModel(
            name='TrialBalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_balanced', models.BooleanField(default=True)),
                ('data_snapshot', models.JSONField(help_text='JSON dump of account balances')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
        ),
    ]
