# Generated by Django 6.0 on 2026-01-23 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_business_is_intercompany_enabled_business_parent_and_more'),
        ('ledger', '0009_daybook_profitandlosssnapshot_trialbalancesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('periods', models.PositiveIntegerField(help_text='Number of months')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_account', models.ForeignKey(help_text='e.g. Prepaid Insurance', on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_schedules', to='ledger.account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('expense_account', models.ForeignKey(help_text='e.g. Insurance Expense', on_delete=django.db.models.deletion.CASCADE, related_name='expense_schedules', to='ledger.account')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedule', to='ledger.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='AmortizationMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_posted', models.BooleanField(default=False)),
                ('journal_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.voucher')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='ledger.amortizationschedule')),
            ],
        ),
    ]
