# Generated by Django 6.0 on 2026-01-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_document_core_docume_busines_4c79f9_idx_and_more'),
        ('ledger', '0010_amortizationschedule_amortizationmovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterField(
            model_name='account',
            name='classification',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, default='ASSET', max_length=20),
        ),
        migrations.AlterField(
            model_name='amortizationschedule',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedules', to='core.business'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ref_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['business', 'classification'], name='ledger_acco_busines_84569e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['business', 'group'], name='ledger_acco_busines_f32bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['account', 'debit', 'credit'], name='ledger_jour_account_c06f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['voucher', 'account'], name='ledger_jour_voucher_7025dd_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['ref_number'], name='ledger_jour_ref_num_0c7c91_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['business', 'date'], name='ledger_vouc_busines_7e32b7_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['business', 'voucher_type'], name='ledger_vouc_busines_e3359d_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['business', 'is_draft'], name='ledger_vouc_busines_0da9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['date'], name='ledger_vouc_date_377b85_idx'),
        ),
    ]
