# Generated by Django 6.0 on 2026-01-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_remove_daybook_amount_account_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
